### PR TITLE
fix: use domain qualified finalizers in the default policy server.

### PR DESCRIPTION
**Pull request by jvanz**
## Description

Updates the default policy server to use domain qualified finalizer and follow the change in the controller as well.

Related to https://github.com/kubewarden/kubewarden-controller/issues/728

## Test

Manual testing

### CODE REVIEW

**Comment by viccuad** [comment]
This needs to go on 1.14 and not 1.13, as controller 1.13 is already tagged.

**Review by flavio — APPROVED** [review]
Let's merge it after 1.13 is out

**Comment by flavio** [comment]
Moving to blocked, since we're waiting for the 1.13 release to be over

**Comment by viccuad** [comment]
1.13 out, unblocking.

**Pull request merged**
