### PR TITLE
feat: questions for tolerations and affinity.

### PR DESCRIPTION
**Pull request by jvanz**
## Description

Updates the questions.yaml file adding two more questions to allow users define the tolerations and affinity used in the Helm charts via Rancher UI.

### CODE REVIEW

**Review by flavio — APPROVED** [review]

**Review by viccuad — COMMENTED** [review]
LGTM. Yet, does the `type: yaml` work already?

I hit the following last time:
https://github.com/rancher/dashboard/issues/10814
https://github.com/rancher/dashboard/issues/10815

**Comment by jvanz** [comment]
> @jvanz let's give it a try to make sure everything works fine

Yeah, unfortunately we are still facing the issues reported by @viccuad on Rancher 2.8.5.

**Comment by jvanz** [comment]
Folks, I'm trying to add questions entries to map the new configuration. But the Rancher dashboard has issues that is making this extremely hard. It lack some features. This is also highlighted by @viccuad in this [comment](https://github.com/kubewarden/helm-charts/issues/418#issuecomment-2059191129). 

With the in mind, I think we should keep that out of the questions.yml until Rancher dashboard fixes the blocking issues

**Comment by viccuad** [comment]
I would suggest adding the questions but commented for now, with a link to the issues.

**Comment by jvanz** [comment]
> I would suggest adding the questions but commented for now, with a link to the issues.

I personally do not like having code not use in the file. It makes it harder to read and maintain. I would prefer update the [issue](https://github.com/kubewarden/helm-charts/issues/418) and wait for the fixes.

**Comment by viccuad** [comment]
I'm ok with that, let's open an issue, and link and close this PR then.

**Comment by jvanz** [comment]
> I'm ok with that, let's open an issue, and link and close this PR then.

https://github.com/kubewarden/helm-charts/issues/483

**Pull request closed without merging**
