### PR TITLE
Policy group files

### PR DESCRIPTION
**Pull request by jvanz**
## Description
Updates the Helm charts to have the files required by the controller to be able to reconcile policy group types.

Fix https://github.com/kubewarden/kubewarden-controller/issues/857

### CODE REVIEW

**Review by flavio — APPROVED** [review]
LGTM

**Comment by flavio** [comment]
Moving to blocked, we have to wait for https://github.com/kubewarden/kubewarden-controller/issues/872 to be fixed, then copy the correct CRDs definitions into this PR

**Review by flavio — CHANGES_REQUESTED** [review]
Waiting for https://github.com/kubewarden/kubewarden-controller/issues/872 to be solved

**Review by fabriziosestito — APPROVED** [review]

**Review by viccuad — APPROVED** [review]

**Comment by viccuad** [comment]
We have decided to merge this to unblock the E2E tests.

Once we have https://github.com/kubewarden/kubewarden-controller/issues/872, we will bump the Helm charts with the CRDs accordingly.

**Pull request merged**
