### PR TITLE
docs: Add CONTRIBUTING.md with release steps

### PR DESCRIPTION
**Pull request by viccuad**

### CODE REVIEW

**Comment by viccuad** [comment]
Cancelled E2E tests, no need.

**Comment by olblak** [comment]
@viccuad What would you think to move the release procedure to an issue template? 
Then each time we need to create a new release, we open an "issue" of type "release",   

Any further modification of the release process must be done via the issue template

An example of how we do this on the Epinio project is we have this issue template:
* [Issue Template](https://github.com/epinio/epinio/blob/main/.github/ISSUE_TEMPLATE/release_checklist.yaml)
* [Release ticket](https://github.com/epinio/epinio/issues/2571)

**Review by flavio — APPROVED** [review]
thanks!

**Comment by viccuad** [comment]
@olblak that's a nice approach, but I don't have the bandwidth now to provide a full itemized list, this was just a quick docs PR.

**Pull request merged**
